### ISSUE TITLE
 Deployment script exits with error if there's any warnings at pytest step

### ISSUE THREAD

**Issue by noemifrisina** [DiamondLightSource/mx-bluesky#171]
Running the deployment script currently does not complete but exits with the error:
```
ERROR:   tests: parallel child exit code 1
  docs: commands succeeded
Traceback (most recent call last):
  File "/scratch/uhz96441/workspaces/mx-bluesky/./deploy/deploy_mxbluesky.py", line 169, in <module>
    run_process_and_print_output("./dls_dev_setup.sh")
  File "/scratch/uhz96441/workspaces/mx-bluesky/./deploy/deploy_mxbluesky.py", line 124, in run_process_and_print_output
    raise CalledProcessError(p.returncode, p.args)
subprocess.CalledProcessError: Command './dls_dev_setup.sh' returned non-zero exit status 1.
```

This happens because of [this](https://iscinumpy.gitlab.io/post/bound-version-constraints/#watch-for-warnings) , which is good to have but causes the deployment script to exit before completing. 
As this is after the virtual environment is installed, only minor tasks are left over, such as creating the softlinks. While we can take care of this at a later time, we should have a deployment script that goes through all the steps if the virtual environment is installed.

## Steps To Reproduce
1. From your local environment run the deployment script with `--dev-path`

## Acceptance Criteria
- Deployment completes correctly

**Comment by noemifrisina** [comment]
Underlining issue causing this is this DeprecationWarning:
```
ERROR tests/test_example.py - DeprecationWarning: The 'wheel' package is no longer the canonical location of the 'bdist_wheel' command, and will be removed in a future release. Please update to setuptools v70.1 or later which contains an integrated version of this command.
```

**Comment by DominicOram** [comment]
The depreciation warning is happening because https://github.com/epics-base/setuptools_dso is getting `bdist_wheel` from `wheel`. As of `wheel` version 0.44.0 and this lives in `setuptools` v70.1 this is inside `setuptools` itself.

**Comment by DominicOram** [comment]
See https://github.com/epics-base/setuptools_dso/issues/36

**Comment by dperl-dls** [comment]
fixing the deprecation is good, but do we want this to always stop deployment? we could run the deployment tests with `filterwarnings` turned off
