### ISSUE TITLE
I24 SSX: Take into account zoom in click to move

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/mx-bluesky#44]
Currently the click to move has a hardcoded scale factor for pixels to microns. We should instead get the scale from the OAVParameters and we should make sure it's updated on zoom level

**Comment by DominicOram** [comment]
Should probably do https://github.com/DiamondLightSource/mx_bluesky/issues/42 first

**Comment by DominicOram** [comment]
We may also need to do https://github.com/DiamondLightSource/mx_bluesky/issues/54 first

**Comment by noemifrisina** [comment]
OAVParameters related issue from testing on 14/11/23

Viewer opens fine but it gets shut off after a bit with the following error:

```Showing camera feed. Press escape to close
Clicked X and Y 827 266
Moving X and Y 1134 756
Clicked X and Y 684 467
Moving X and Y 276 -450
Clicked X and Y 528 596
Moving X and Y -660 -1224
Traceback (most recent call last):
  File "/dls_sw/i24/software/bluesky/mx_bluesky/src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py", line 59, in onMouse
  File "/dls_sw/i24/software/bluesky/mx_bluesky/src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py", line 54, in get_beam_centre_from_oav
  File "/dls_sw/i24/software/bluesky/mx_bluesky/src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py", line 38, in _get_beam_centre
  File "/dls_sw/i24/software/bluesky/mx_bluesky/.venv/lib/python3.10/site-packages/bluesky/run_engine.py", line 364, in __init__
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/asyncio/events.py", line 783, in new_event_loop
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/asyncio/events.py", line 673, in new_event_loop
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/asyncio/unix_events.py", line 64, in __init__
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/asyncio/selector_events.py", line 56, in __init__
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/asyncio/selector_events.py", line 103, in _make_self_pipe
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/socket.py", line 607, in socketpair
OSError: [Errno 24] Too many open files
Exception ignored in: <function BaseEventLoop.__del__ at 0x7fed02b84ca0>
Traceback (most recent call last):
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/asyncio/base_events.py", line 690, in __del__
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/asyncio/unix_events.py", line 68, in close
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/asyncio/selector_events.py", line 87, in close
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/asyncio/selector_events.py", line 94, in _close_self_pipe
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_ssock'
Traceback (most recent call last):
  File "/dls_sw/i24/software/bluesky/mx_bluesky/src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py", line 59, in onMouse
  File "/dls_sw/i24/software/bluesky/mx_bluesky/src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py", line 52, in get_beam_centre_from_oav
  File "/dls_sw/i24/software/bluesky/dodal/src/dodal/devices/oav/oav_parameters.py", line 35, in __init__
  File "/dls_sw/i24/software/bluesky/dodal/src/dodal/devices/oav/oav_parameters.py", line 49, in load_json
OSError: [Errno 24] Too many open files: '/dls_sw/i24/software/daq_configuration/json/OAVCentring.json'
Traceback (most recent call last):
  File "/dls_sw/i24/software/bluesky/mx_bluesky/src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py", line 215, in <module>
  File "/dls_sw/i24/software/bluesky/mx_bluesky/src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py", line 169, in start_viewer
  File "/dls_sw/i24/software/bluesky/mx_bluesky/src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py", line 73, in update_ui
  File "/dls_sw/i24/software/bluesky/mx_bluesky/src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py", line 52, in get_beam_centre_from_oav
  File "/dls_sw/i24/software/bluesky/dodal/src/dodal/devices/oav/oav_parameters.py", line 35, in __init__
  File "/dls_sw/i24/software/bluesky/dodal/src/dodal/devices/oav/oav_parameters.py", line 49, in load_json
OSError: [Errno 24] Too many open files: '/dls_sw/i24/software/daq_configuration/json/OAVCentring.json'
Traceback (most recent call last):
  File "/dls_sw/i24/software/bluesky/mx_bluesky/src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py", line 59, in onMouse
  File "/dls_sw/i24/software/bluesky/mx_bluesky/src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py", line 54, in get_beam_centre_from_oav
  File "/dls_sw/i24/software/bluesky/mx_bluesky/src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py", line 38, in _get_beam_centre
  File "/dls_sw/i24/software/bluesky/mx_bluesky/.venv/lib/python3.10/site-packages/bluesky/run_engine.py", line 364, in __init__
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/asyncio/events.py", line 783, in new_event_loop
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/asyncio/events.py", line 673, in new_event_loop
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/asyncio/unix_events.py", line 64, in __init__
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/asyncio/selector_events.py", line 56, in __init__
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/asyncio/selector_events.py", line 103, in _make_self_pipe
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/socket.py", line 607, in socketpair
OSError: [Errno 24] Too many open files
Exception ignored in: <function BaseEventLoop.__del__ at 0x7fed02b84ca0>
Traceback (most recent call last):
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/asyncio/base_events.py", line 690, in __del__
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/asyncio/unix_events.py", line 68, in close
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/asyncio/selector_events.py", line 87, in close
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/asyncio/selector_events.py", line 94, in _close_self_pipe
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_ssock'
Traceback (most recent call last):
  File "/dls_sw/i24/software/bluesky/mx_bluesky/src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py", line 59, in onMouse
  File "/dls_sw/i24/software/bluesky/mx_bluesky/src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py", line 52, in get_beam_centre_from_oav
  File "/dls_sw/i24/software/bluesky/dodal/src/dodal/devices/oav/oav_parameters.py", line 35, in __init__
  File "/dls_sw/i24/software/bluesky/dodal/src/dodal/devices/oav/oav_parameters.py", line 49, in load_json
OSError: [Errno 24] Too many open files: '/dls_sw/i24/software/daq_configuration/json/OAVCentring.json'
Traceback (most recent call last):
  File "/dls_sw/i24/software/bluesky/mx_bluesky/src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py", line 215, in <module>
  File "/dls_sw/i24/software/bluesky/mx_bluesky/src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py", line 169, in start_viewer
  File "/dls_sw/i24/software/bluesky/mx_bluesky/src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py", line 73, in update_ui
  File "/dls_sw/i24/software/bluesky/mx_bluesky/src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py", line 52, in get_beam_centre_from_oav
  File "/dls_sw/i24/software/bluesky/dodal/src/dodal/devices/oav/oav_parameters.py", line 35, in __init__
  File "/dls_sw/i24/software/bluesky/dodal/src/dodal/devices/oav/oav_parameters.py", line 49, in load_json
OSError: [Errno 24] Too many open files: '/dls_sw/i24/software/daq_configuration/json/OAVCentring.json'
```

This issue should get fixed by [Dodal224](https://github.com/DiamondLightSource/dodal/issues/224), which is also needed before proceeding with this issue.

**Comment by noemifrisina** [comment]
The OSError above seems to have been cause by the same file being opened in another process at the same time.
