### ISSUE TITLE
 Hyperion unit tests failing on i24 

### ISSUE THREAD

**Issue by noemifrisina** [DiamondLightSource/mx-bluesky#533]
When running tests in the environment in `/dls_sw/i24/software/...` , several hyperion unit tests seem to be failing, eg:

```
FAILED tests/unit_tests/hyperion/experiment_plans/test_flyscan_xray_centre_plan.py::TestFlyscanXrayCentrePlan::test_flyscan_xray_centre_sets_directory_stages_arms_disarms_unstages_the_panda - AssertionError: Attempt to open /dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/src/mx_bluesky/hyperion/resources/panda/panda-gridscan.yaml from inside a unit test
assert not True
 +  where True = is_relative_to(PosixPath('/dls_sw'))
 +    where is_relative_to = PosixPath('/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/src/mx_bluesky/hyperion/resources/panda/panda-gridscan.yaml').is_relative_to
```
with stack trace:
```
_ TestFlyscanXrayCentrePlan.test_given_setting_stub_offsets_disabled_then_stub_offsets_not_set[panda] _
Traceback (most recent call last):
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/_pytest/runner.py", line 341, in from_call
    result: TResult | None = func()
                             ^^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/_pytest/runner.py", line 242, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/_pytest/threadexception.py", line 92, in pytest_runtest_call
    yield from thread_exception_runtest_hook()
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/_pytest/threadexception.py", line 68, in thread_exception_runtest_hook
    yield
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/_pytest/unraisableexception.py", line 95, in pytest_runtest_call
    yield from unraisable_exception_runtest_hook()
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/_pytest/unraisableexception.py", line 70, in unraisable_exception_runtest_hook
    yield
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/_pytest/logging.py", line 846, in pytest_runtest_call
    yield from self._runtest_for(item, "call")
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/_pytest/logging.py", line 829, in _runtest_for
    yield
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/_pytest/capture.py", line 880, in pytest_runtest_call
    return (yield)
            ^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/_pytest/skipping.py", line 257, in pytest_runtest_call
    return (yield)
            ^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/_pytest/runner.py", line 174, in pytest_runtest_call
    item.runtest()
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/pytest_asyncio/plugin.py", line 457, in runtest
    super().runtest()
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/_pytest/python.py", line 1627, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/pluggy/_callers.py", line 182, in _multicall
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/pluggy/_result.py", line 100, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/_pytest/python.py", line 159, in pytest_pyfunc_call
    result = testfunction(**testargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/pytest_asyncio/plugin.py", line 929, in inner
    _loop.run_until_complete(task)
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.11/lib/python3.11/unittest/mock.py", line 1386, in patched
    return await func(*newargs, **newkeywargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/tests/unit_tests/hyperion/experiment_plans/test_flyscan_xray_centre_plan.py", line 817, in test_given_setting_stub_offsets_disabled_then_stub_offsets_not_set
    RE(
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/bluesky/run_engine.py", line 964, in __call__
    plan_return = self._resume_task(init_func=_build_task)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/bluesky/run_engine.py", line 1100, in _resume_task
    raise exc
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/bluesky/run_engine.py", line 1734, in _run
    raise err
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/bluesky/run_engine.py", line 1588, in _run
    msg = self._plan_stack[-1].send(resp)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/bluesky/preprocessors.py", line 358, in run_wrapper
    yield from contingency_wrapper(plan, except_plan=except_plan, else_plan=close_run)
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/bluesky/preprocessors.py", line 604, in contingency_wrapper
    ret = yield from plan
          ^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/tests/unit_tests/hyperion/experiment_plans/test_flyscan_xray_centre_plan.py", line 809, in wrapped_gridscan_and_move
    yield from run_gridscan_and_move(
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/bluesky/utils/__init__.py", line 1246, in dec_inner
    return (yield from plan)
            ^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/bluesky/preprocessors.py", line 1395, in set_run_key_wrapper
    return (yield from msg_mutator(plan, _set_run_key))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/bluesky/preprocessors.py", line 271, in msg_mutator
    msg = plan.send(_s)
          ^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/bluesky/utils/__init__.py", line 1246, in dec_inner
    return (yield from plan)
            ^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/bluesky/preprocessors.py", line 358, in run_wrapper
    yield from contingency_wrapper(plan, except_plan=except_plan, else_plan=close_run)
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/bluesky/preprocessors.py", line 604, in contingency_wrapper
    ret = yield from plan
          ^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/src/mx_bluesky/hyperion/experiment_plans/flyscan_xray_centre_plan.py", line 183, in run_gridscan_and_move
    yield from feature_controlled.setup_trigger(fgs_composite, parameters, initial_xyz)
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/src/mx_bluesky/hyperion/experiment_plans/flyscan_xray_centre_plan.py", line 516, in _panda_triggering_setup
    yield from setup_panda_for_flyscan(
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/src/mx_bluesky/hyperion/device_setup_plans/setup_panda.py", line 151, in setup_panda_for_flyscan
    yield from load_device(panda, str(config_yaml_path))
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/ophyd_async/core/_device_save_loader.py", line 226, in load_device
    values = load_from_yaml(path)
             ^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/.venv/lib/python3.11/site-packages/ophyd_async/core/_device_save_loader.py", line 166, in load_from_yaml
    with open(save_path) as file:
         ^^^^^^^^^^^^^^^
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.11/lib/python3.11/unittest/mock.py", line 1118, in __call__
    return self._mock_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.11/lib/python3.11/unittest/mock.py", line 1122, in _mock_call
    return self._execute_mock_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.11/lib/python3.11/unittest/mock.py", line 1183, in _execute_mock_call
    result = effect(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/tests/unit_tests/hyperion/conftest.py", line 20, in patched_open
    assert not requested_path.is_relative_to(
AssertionError: Attempt to open /dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/src/mx_bluesky/hyperion/resources/panda/panda-gridscan.yaml from inside a unit test
assert not True
 +  where True = is_relative_to(PosixPath('/dls_sw'))
 +    where is_relative_to = PosixPath('/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/src/mx_bluesky/hyperion/resources/panda/panda-gridscan.yaml').is_relative_to
```

Another example:

```
FAILED tests/unit_tests/hyperion/external_interaction/callbacks/test_external_callbacks.py::test_setup_logging - AssertionError: Attempt to open /dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/tmp/dev/hyperion_ispyb_callback.log from inside a unit test
assert not True
 +  where True = is_relative_to(PosixPath('/dls_sw'))
 +    where is_relative_to = PosixPath('/dls_sw/i24/software/bluesky/mx-bluesky_v1.1.0/mx-bluesky/tmp/dev/hyperion_ispyb_callback.log').is_relative_to
```

These tests are fine in a local dev installation.

## Steps To Reproduce
1. Go to '/dls_sw/i24/software/bluesky/mx-bluesky'
2. Activate the local environment
3.Run `pytest -m "not s03"

## Acceptance Criteria
- Hyperion unit tests can run on any beamline

**Comment by DominicOram** [comment]
Fixed by https://github.com/DiamondLightSource/mx-bluesky/pull/749
